- hosts: minecraft
  become: true
  tasks:
    - name: Install Java 21
      apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    - name: Create Minecraft directory
      file:
        path: /home/ubuntu/minecraft
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ubuntu/minecraft/server.jar
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Accept EULA
      copy:
        dest: /home/ubuntu/minecraft/eula.txt
        content: "eula=true\n"
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          ExecStop=/bin/kill -s SIGINT $MAINPID
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
